question_data = [
    {"text": "Baník Ostrava získal svůj první titul mistra Československa v roce 1976", "answer": "False"},
    {"text": "Baník Ostrava byl založen v roce 1922 jako SK Slezská Ostrava", "answer": "True"},
    {"text": "V sezóně 2003/2004 Baník Ostrava vyhrál českou nejvyšší ligu", "answer": "True"},
    {"text": "Stadion Bazaly byl domovským stadionem Baníku až do roku 2014", "answer": "True"},
    {"text": "Baník Ostrava odehrál své domácí zápasy v sezóně 2020/2021 na Městském stadionu v Ostravě-Vítkovicích", "answer": "True"},
    {"text": "Baník Ostrava nikdy nehrál semifinále evropského poháru", "answer": "False"},
    {"text": "Baník Ostrava má ve znaku symbol hornictví", "answer": "True"},
    {"text": "Nejvíce ligových gólů za Baník Ostrava vstřelil Milan Baroš", "answer": "False"},
    {"text": "V roce 1980 Baník vyhrál Československý pohár", "answer": "True"},
    {"text": "Baník Ostrava je přezdíván „Chachaři“", "answer": "True"},
    {"text": "Historicky nejúspěšnějším trenérem Baníku je Evžen Hadamczik", "answer": "True"},
    {"text": "Baník Ostrava nikdy nesestoupil do druhé ligy", "answer": "False"},
    {"text": "Milan Baroš ukončil kariéru právě v dresu Baníku Ostrava", "answer": "True"},
    {"text": "V 70. letech hrál za Baník známý útočník Václav Daněk", "answer": "False"},
    {"text": "Baník Ostrava má více než 5 titulů mistra ligy", "answer": "False"},
    {"text": "Největšími rivaly Baníku jsou Sparta Praha a Sigma Olomouc", "answer": "True"},
    {"text": "Baník Ostrava má partnerský klub v Polsku", "answer": "True"},
    {"text": "V roce 2005 Baník Ostrava sestoupil do druhé ligy", "answer": "False"},
    {"text": "Baník Ostrava se účastnil základní skupiny Ligy mistrů UEFA", "answer": "False"},
    {"text": "Před přestěhováním na Městský stadion proběhla rozsáhlá rekonstrukce Bazalů", "answer": "False"},
    {"text": "Baník Ostrava hraje tradičně v modro-bílých dresech", "answer": "True"},
    {"text": "Slavný obránce Tomáš Ujfaluši začínal kariéru v Baníku Ostrava", "answer": "True"},
    {"text": "Baník Ostrava byl založen během první světové války", "answer": "False"},
    {"text": "V historii Baníku nikdy nepůsobil žádný zahraniční trenér", "answer": "False"},
    {"text": "Legendární brankář Jan Laštůvka chytal za Baník Ostrava", "answer": "True"},
    {"text": "Baník Ostrava měl v minulosti sekci házené", "answer": "True"},
    {"text": "Baník Ostrava má svůj oficiální fanklub známý jako Bazal Boys", "answer": "False"},
    {"text": "Baník Ostrava nikdy nehrál finále domácího poháru", "answer": "False"},
    {"text": "Z Baníku Ostrava vzešlo několik českých reprezentantů", "answer": "True"},
    {"text": "Kapitánem Baníku Ostrava v roce 2022 byl Daniel Holzer", "answer": "False"}
]
